### ISSUE TITLE
Can't open on M1 Mac...

### ISSUE THREAD

**Issue by ChopsKingsland** [UnusAnnusArchived/TUAA-Downloader#1]
I am trying to open this on an M1 Mac, but it won't open... I get the following error:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/18499854/116929972-0d49ba80-ac57-11eb-8762-59821ab09eba.png">

Any help appreciated...

**Comment by ghost** [comment]
Hey, I'm not able to reproduce this, but I might know what could be causing it.

Can you open Terminal (can be found in spotlight or in the Other folder in Launchpad), and type the following command?
```
chmod +x <location of app>/Contents/MacOS/The\ Unus\ Annus\ Archive\ Downloader
```
(to get the location of the app, you can drag it to the terminal window and it'll autofill it for you)

This should add the execute permission to the app's executable, which should fix it if what I'm thinking is correct.

**Comment by ChopsKingsland** [comment]
I have done that, and now I get this... 
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/18499854/117578241-54b3c900-b0e5-11eb-811e-ba04fe57be22.png">

**Comment by ghost** [comment]
Did you extract the .zip using any 3rd party unzipping software? If you did could you try again with the built in Archive Utility app and see if that fixes the issue?

**Comment by ChopsKingsland** [comment]
I only use Archive Utility, because it is a lot easier than 3rd party ones...

**Comment by ghost** [comment]
Would you know how to build an electron app yourself so you can see if building it natively on your machine would fix it?

**Comment by ghost** [comment]
I've now actually been able to recreate this issue, so I will do my own testing to try and solve the issue.

**Comment by ghost** [comment]
Can you try this new file for me and see if it works?
https://cdn.unusann.us/github-issue-files/TUAA-Downloader/%231/The%20Unus%20Annus%20Archive%20Downloader-1.0.1.dmg

**Comment by issiwizzi** [comment]
hello! i also have a mac computer and I clicked the new file that you sent above but still will. not let me access it. i have it on my desktop but when I click on it it says this
<img width="421" alt="Screen Shot 2021-05-14 at 1 21 58 AM" src="https://user-images.githubusercontent.com/84171435/118230157-ccba2000-b452-11eb-913c-36566081519f.png">

**Comment by ChopsKingsland** [comment]
@issiwizzi to fix that issue, you have to go to `System Preferences > Security & Privacy > Open Anyway at the bottom of general`

**Comment by EverlyScott** [comment]
> @issiwizzi to fix that issue, you have to go to `System Preferences > Security & Privacy > Open Anyway at the bottom of general`

you can also right click (ctrl+click) on the app and hit open, then on the pop up it allows you to open it

**Comment by ghost** [comment]
I've gotten someone else with that same issue to test that the dmg works and it does so I'm pretty sure that fixed it.
